spring:
  application:
    name: fileservice
  config:
    import: optional:configserver:http://localhost:8071/

#  kafka:
#    bootstrap-servers: localhost:9095
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



logging:
  level:
    org.hibernate.SQL: DEBUG